### ISSUE TITLE
Build 4: New customer invoice > customer searching > doesn't display all the customer list

### ISSUE THREAD

**Issue by bijaySussol** [sussol/mobile#121]
Should have a scrollbar or something to scroll all the customer.

See image attached !
![screenshot_2016-07-16-23-43-05](https://cloud.githubusercontent.com/assets/13144882/16899894/0b614582-4c33-11e6-80ce-0b5f12d32661.png)

**Comment by Chris-Petty** [comment]
fixed in #604
