### ISSUE TITLE
Pending sync record statistic would be great 

### ISSUE THREAD

**Issue by ujwalSussol** [sussol/mobile#346]
Build Number: 20

Description: Like mSupply we need a message that says  XX sync record to send ......   this will make the user aware.

Reproducible:

Reproduction Steps:

Comments:

**Comment by ujwalSussol** [comment]
@Chris-Petty   While testing mSupply mobile, I still think we need a text on the main navigator stressing the number of data waiting to be synced....    On our desktop app the information on the navigator actually helps the Nigerian user to switch on their internet....  Some places use the internet in a very stingy manner.

**Comment by Chris-Petty** [comment]
This should be really easy to do at the moment, just adding it to the manual sync modal. Would that be enough or would you push for being in the top navigation bar? Picture of sync modal for context:
![image](https://user-images.githubusercontent.com/7684221/30527909-ede750fa-9c81-11e7-9bab-e3280b96248a.png)

We could add some indicator of number of sync records here.

**Comment by Chris-Petty** [comment]
@ujwalSussol Would the below be sufficient?

![image](https://user-images.githubusercontent.com/7684221/32259859-73e92ec6-bf28-11e7-8794-a3212fc41182.png)
