### ISSUE TITLE
Can't see store that a tablet is synced to from login

### ISSUE THREAD

**Issue by fergussussol** [sussol/mobile#374]
Build Number: 28

Description: No way to tell what store tablet is synced to

Reproducible: yep

Reproduction Steps: 

Comments:

Had a situation in Timor where there might have been tablets swapped around. The only way to tell from software which store a tablet is synced to is by trying a login that ought to work with that store and seeing if it works... Somewhat tedious.

Could we have the store reported on the login screen?

**Comment by Chris-Petty** [comment]
fixed in #409
