### ISSUE TITLE
Crash when remotely deleting stock takes

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#382]
Build Number: 30

Description: Remotely accessing Solomons tablet for Gizo that had just synced with old mobile data. Went into old stock takes and selected all the (8) stock takes with the intent to delete them. Click and hold on the delete button and dragged up, as I saw one was in 2016 and wanted to investigate. Crashed back to main screen with usual system error.

Reproducible: No. Tried again including dragging the delete button. Deleted the stock takes without any issue.

Reproduction Steps:

Comments: Normally I'd put a crash as high, but I don't have any idea what caused it at this point and can't reproduce it. Medium seems fair.

**Comment by andreievg** [comment]
close due to inactivity.

**Comment by GaryWilletts** [comment]
Is that a good reason for closing an issue?

**Comment by andreievg** [comment]
Very old build number + only happened once + can't reproduce

**Comment by Chris-Petty** [comment]
Yea generally not but as Andrei said. The main one being that I couldn't even reproduce it at the time. A crash like this should be picked up and logged (and new issue here made automatically) buy bugsnag, so I think we're good.
