### ISSUE TITLE
Add status to requisitions

### ISSUE THREAD

**Issue by edmofro** [sussol/mobile#388]
From Michael: "Is it possible for clinics to see the current status of their requisition (Authorised, Rejected, Suggested, Confirmed, Finalised...). At the moment, they send it off and they have no idea what's happening with it until it becomes a Supplier Invoice or it disappears. A status would be very cool, they all requested this and I agree it would be useful."

**Comment by andreievg** [comment]
Request requisition should only be edited by the store the requisition belongs to.  Supply requisition is updated with status, which should not affect request requisition, so the Mobile store that made request requisition does not know about it's status.
We will be breaking a sync assumption if we are to update a record on another site (not the one it belongs to).
Closing this issue.
