### ISSUE TITLE
Handle Item and Name merging

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#392]
This is handling the receipt of a merge record from the primary server- you have to merge the records locally in code. There is no need to provide a UI for merging items and names on mobile.

[View on Kanboard](http://kanban.sussol.net/?controller=TaskViewController&action=show&task_id=1965&project_id=8)

**Comment by edmofro** [comment]
As well as names and items, you can merge
- Units
- Locations
- Prescribers
Fortunately, we don't keep any of those in mobile, so don't worry about them!

**Comment by edmofro** [comment]
From Adrian:

Incoming merge records are not processed immediately as they come in (in case a later record in the same batch of sync records also needs merged), so it temporarily stores the merge information in a pref_blob.

The sync_process_merge_apply() then runs immediately after processing incoming and outgoing records - it processes these pref_blob records and calls separate methods which merge items, names, units, locations and prescribers. Each of these methods has a similar structure - basically updating the secondary keys in any tables which reference the deleted record. Mobile will need to do something similar, but with a lot less tables to worry about.

**Comment by edmofro** [comment]
Duplicate of #160, closing.
