### ISSUE TITLE
Allow creating new supplier invoices (not from central supplier)

### ISSUE THREAD

**Issue by edmofro** [sussol/mobile#401]
Motivation:
Stores sometimes get medicines from someone other than their main supplier. For example, they might run out of paracetamol, and buy some new stocks from the local private pharmacy. Or a donor might turn up with a whole lot of asthma inhalers. We need to allow them to enter this stock into inventory in a more elegant way that just increasing stock through a stocktake.

Solution:
On the Supplier Invoices page, have a 'New Invoice' button. This matches the functionality of the analogous button on the Customer Invoices page: clicking it brings up a list of Suppliers (defined on the central server) which can be filtered and selected. Selecting a supplier creates a new supplier invoice with that supplier connected, with the ability to add item lines.

Gotchas:
- We still don't want to confuse mobile by adding batch and expiry information, so just add the batches with none (much like we do for a stocktake that has no existing lines to increase)
- What prices to use?

**Comment by andreievg** [comment]
Feature implemented in -> https://github.com/sussol/mobile/releases/tag/v2.0.0
