### ISSUE TITLE
Item usage calculations wrong if batch runs out

### ISSUE THREAD

**Issue by gkaplan** [sussol/mobile#405]
Build Number: 30

Description: The app appears to underestimate item consumption when stock of a batch lasts for less than 90 days. If my starting balance of a batch in month 1 is 150 units, and I use 150 units in month 1 (5 units per day), then when I go to order at the end of month 3 it looks like my usage for that batch would be calculated as being ~1.6 units a day. I've put together a [small spreadsheet example](https://docs.google.com/spreadsheets/d/1dUDp2xsVnBWyAJx1lXjonklDZpSSXHadAbeSi0z4SWU/edit?usp=sharing) to illustrate this.

Comments: Hi SusSol team, congrats on the launch of the tablet app! It's very exciting that it's open source too! This is purely based on me looking at the code, which I may have misunderstood - corrections welcome. :smile:

**Comment by Chris-Petty** [comment]
I believe our assumption in this case is that for the last 3 months, that is the correct average consumption.

I think this is fine, but where you're heading to I think is that there is potential to improve the suggested quantity calculation in requisitions to have a more informed algorithm . Currently it's up to the user to realise they need a larger amount than the suggested quantity.
