### ISSUE TITLE
Item usage not aggregated across batches correctly

### ISSUE THREAD

**Issue by gkaplan** [sussol/mobile#406]
Build Number: 30

Description: It looks like item.dailyUsage() is summing the dailyUsage for each batch, which would over-estimate usage when there are multiple batches. If daily usage for batch 1 is 15, and daily usage for batch 2 is also 15, it looks like item.dailyUsage() would return 30. The spreadsheet example linked in issue #405 also includes something about this. It seems like the correct approach to get the total daily usage for an item across batches would be to sum up the total usage for all batches and the number of days each batch was used, then do the division in Item.

Comments: Happy to take a crack at this ticket or #405, but I don't have a server I could test on at the moment..

**Comment by Chris-Petty** [comment]
Hey @gkaplan thanks for checking out our code! And nice catch. `dailyUsage()` could be more verbosely called `averageDailyUseOverLastNinetyDays()` ;)

If we followed that correctly, summing the averages of each batch should be fine as 15+15/90 is the same as 15/90 + 15/90

That said, it doesn't necessarily do that if a batch is less than 90 days old. Say it's one day old, then it is 15/1 + 15/90 which would give a large over estimate for the last 90 days.

In short, I agree that the division should be done at the top in `Item`.

`itemBatch.dailyUsage()` should probably get deprecated.

`itemBatch.totalUsageForPeriod(startDate, endDate)`: sums the total transaction usage in the given period.

`item.totalUsageForPeriod(startDate, endDate)`: sums the above on all batches

then
`item.dailyUsage()`: calls the above with (currentDate - 90days, currentDate)
and/Or
`item.dailyUsageForPeriod(startDate, endDate)`: calls the above and divides by the period length in days (rounding up).

**Comment by gkaplan** [comment]
Hi @Chris-Petty, sorry for the slow reply, was on vacation :). 

It sounds like we're on the same page about how to change the calculation. The only thing I'm not clear about is how the period length would be calculated - I hope it would account for stock outs? 

For example: I use 300 units of an item for 15 days, I stock out for 30 days, then I receive a replenishment and I use 900 units for 45 days, I hope that the usage calculated would be 1200 units / 60 days = 20 units avg daily usage rather than 1200 units / 90 days = ~13.3 units avg daily usage. 

Potentially you could approximate the period for each batch by looking at the date of the last transaction if the batch has no stock minus date of the earliest transaction, max 90 days ago, and then sum the period across batches in the same way as you're proposing to sum the usage.

**Comment by craigdrown** [comment]
@gkaplan we find the problem with this is that facilities often have rebound usage when they come back into stock which compensates for the stockout period. 
Also, defining "out of stock" is not easy, as having a few tablets kicking around is not technically out of stock, but functionally it is.....
