### ISSUE TITLE
Built in demonstration mode

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#407]
Currently the open source community can't effectively develop mSupply Mobile as there isn't a straight forward backend for them to use. There should be a "Demo mode" button on the first use page for this purpose:

1. Make a demo mode that doesn't have communication with a server, it just has some mock data stored in the APK that gets thrown into the realm, automate locally on device any server response to user (generating supplier invoices for requisitions).

2. Make a public mSupply demo server that automatically makes stores/users for mobile demo mode. Demo mode button hits this server, triggering the creation of above and receiving back the the details to connect and login. Automation of server interactions happens on mSupply end. Delete users/stores after some period.

**Comment by andreievg** [comment]
implemented in: https://github.com/sussol/mobile/pull/724
