### ISSUE TITLE
Stock Item usage lookup

### ISSUE THREAD

**Issue by andreievg** [sussol/mobile#408]
Ability to check average usage per month for an item (or other specified period). Currently can only see when creating a requisition, should be able to look it up (probably best in stock item page)

**Comment by Chris-Petty** [comment]
related #441

**Comment by andreievg** [comment]
https://github.com/sussol/mobile/pull/520

**Comment by Chris-Petty** [comment]
It's better that in #520 top comment to write "fixes #520". This issue will get an automatic reference shown here and when #520 is merged it'll automatically resolve this issue.

**Comment by Chris-Petty** [comment]
Fixed in #520
