### ISSUE TITLE
Stocktake actual quantities inconsistently pre-populated

### ISSUE THREAD

**Issue by andrew-d-uk** [sussol/mobile#420]
Build Number: 30

Description: In a new stocktake, the actual quantity field is sometimes populated with 'No change' and sometimes not populated i.e. appears completely blank. 

Reproducible:

Reproduction Steps:

Comments: This is minor, but can lead to some confusion about whether a completely blank actual quantity field means there is quantity of zero, or no change, being entered.

**Comment by Chris-Petty** [comment]
Thanks Andrew,

This is an interesting one that I have not seen before. Given that it should be easy to replicate by just making a new stock take, it may help if you could let us know the specs of your set up.

Android version:
Tablet Model:
Any other detail I'm not thinking of:
