### ISSUE TITLE
Quantity to issue not saved in customer invoice when tapping 'new item'

### ISSUE THREAD

**Issue by gkaplan** [sussol/mobile#427]
Build Number: 1.1.1

Description: On a customer invoice, after entering the quantity of an item to dispense and pressing add new item, the quantity goes to zero. You have to enter the quantity, tap outside the input box, and then tap add new item for mSupply to keep the quantity you entered. 

Reproducible: Yes

**Comment by Chris-Petty** [comment]
Thanks Grahame,

This is a painful little thing that has been around a long time, thanks for making an issue for it. The changing focus event from the quantity field isn't being triggered correctly.

**Comment by andreievg** [comment]
So this issues is for any field changes in react-native-generic-table-page, on field change if back button or comment edit or any other button on the page is pressed, the field value reverts back to original value.
What happens (say [new item] is clicked in customer invoice)
* Select modal rendering causes the whole page to re-render
* This happens before onEndEditing is called, causing EditableCell (in DataTable) to receive it's value back from props
* even though componentWillReceiveProps in generic-table-page is called and both prop change checks = false, the whole page reload 
* When generic-table-page reloads, react-native-data-table reloads, I've made pr making DataTable a component that check that data source has been changed, it solves this issue: https://github.com/sussol/react-native-data-table/pull/9

**Comment by andreievg** [comment]
And also change in react-native-generic-table-page https://github.com/sussol/react-native-generic-table-page/pull/4 to use the latest react-native-data-table

**Comment by andreievg** [comment]
once both are merged and pushed to npm, will update package.json in mobile

**Comment by Chris-Petty** [comment]
Both merged, nice hunting/fixing. Closing.
