### ISSUE TITLE
Current Stock page improvements

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#429]
Build Number: 1.1.1

Improvements:
- Toggle for hiding stockouts, much like the one when managing a stock take.
- Column that shows the months stock available. Item.quantity/(item.dailyUsage*30days)
- for the number of batches in the expansion, hide those with no stock (discuss if this is appropriate, I think it is)

Extra, though could use it's own issue:
A way via 'Current Stock' to access a ledger view for an individual item. Would need designs done.

**Comment by edmofro** [comment]
@Chris-Petty point three is appropriate, but also, it's happening!

**Comment by andreievg** [comment]
https://github.com/sussol/mobile/releases/tag/v2.1.0-rc1
Improvements to stock page. 
Most of the suggestions have been met, closing the issue
