### ISSUE TITLE
App froze when adding master list items

### ISSUE THREAD

**Issue by DhanyaHerath** [sussol/mobile#435]
Build Number:1.1.3

Description: Tried to add master list items when creating a new customer invoice and the app froze on on the orange square

Reproducible:

Reproduction Steps: Customer Invoice> Create New > Add master list items

Comments: This appears to only happen for customers which don't have masterlists (e.g. in my case, it froze for Patients and TCH General Store, but worked for Tannakoroa)

**Comment by edmofro** [comment]
Fixed in #432

**Comment by Chris-Petty** [comment]
Plot twist, if you don't put the fix keyword in the top description comment of the PR, it won't automatically do anything :(
