### ISSUE TITLE
Translate new lines for Kiribati (comments on code)

### ISSUE THREAD

**Issue by nmadruga** [sussol/mobile#454]
Build Number: v1.2

Description: The translations were added for Timor Leste but still need to be done for Kiribati

Reproducible: The text will appear in english (Requisition page)

**Comment by Chris-Petty** [comment]
In regard to the strings not being translated everywhere, this bugsnag might help: https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59b0f19b5116f1001a47ac61?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open

**Comment by nmadruga** [comment]
Just waiting for the last one to finish

**Comment by Chris-Petty** [comment]
Completed in #539
