### ISSUE TITLE
mobile doesn't handle "pi" (prescription) transaction categories

### ISSUE THREAD

**Issue by adrianwb** [sussol/mobile#457]
Build Number: 30

Description: The merged HNGV/SAMES data file now has some "pi" transaction categories. If one of these is edited on the server, it will generate a sync record for each site (as expected), but this causes mobile to barf and stop sync with the "must be of type String" error. The current #8293 development version of mSupply will filter these out during the initialisation, but won't protect against someone editing one later on.

Reproducible:

Reproduction Steps:

Comments:

**Comment by Chris-Petty** [comment]
Should these be ignored and/or converted to something else and/or handled at a later date?

**Comment by adrianwb** [comment]
AFAIK, they can safely be ignored, until such times as mobile does dispensing at least

**Comment by Chris-Petty** [comment]
Are you sure you that this is happening on latest mobile? I merged Edwin's PR #431 addressing this in June. It was included in the latest release https://github.com/sussol/mobile/releases/tag/v1.1.2 .

**Comment by edmofro** [comment]
Just saw this. Yep, Chris is right, I put in a fix for this when I came across it in Kiribati, so it's been fixed since 1.1.2

Close if you agree @adrianwb
