### ISSUE TITLE
new mobile version should accept response requisitions in v3 API

### ISSUE THREAD

**Issue by adrianwb** [sussol/mobile#458]
Build Number: 30

Description: See comments at https://github.com/sussol/msupply/commit/b145d4364487eb56ff72144dd6319e953035f602#commitcomment-23602591 The simple solution is to allow mobile to accept (and discard?) sync records generated from response requisitions.

Reproducible:

Reproduction Steps:

Comments:

**Comment by nmadruga** [comment]
@adrianwb I believe that one is working, we have V3 receiving request and response that has its mobile store as store_id on requisitions. Can I close this issue?

**Comment by adrianwb** [comment]
Yes, can be closed, thanks
