### ISSUE TITLE
Weird value "placeholderUser" as value in response requisitions

### ISSUE THREAD

**Issue by nmadruga** [sussol/mobile#472]
Build Number: current master (last commit 17/08/17 34a449a27baaab071b4817085c9bedb0282e3a1b)

Description: "Entered By": placeholderUser. We think that would be better just to hide that field in case of response requisition. @edmofro said the format of the Date could be improved also.
![screenshot_20170817-152346](https://user-images.githubusercontent.com/16461988/29396922-19118fa6-836f-11e7-819e-c2556056db7d.png)

Reproducible: Always

Reproduction Steps:

Comments:

**Comment by edmofro** [comment]
This is because the user_ID that comes in with the requisition record is just duplicated by mSupply server from the request requisition that generated this response requisition. So it's the user that entered the original requisition on the requesting site. That kind of does make sense, but seeing as we can't show it here because those users don't sync (is that true @adrianwb?) I have removed entered by from the info section.

**Comment by adrianwb** [comment]
@edmofro Yes, that's right - users don't sync (unless we manually force it) so the receiving site most likely won't have a user record for the person who entered the original request. For response requisitions entered via desktop from the SAMES store, they will have a user_ID from someone at SAMES.

**Comment by edmofro** [comment]
@adrianwb That's fine, we don't need to display the 'Entered By'...no one really cares in mobile, particularly not on a requisition. 

When you say 'For response requisitions entered via desktop from the SAMES store, they will have a user_ID from someone at SAMES.', what does that mean? When a response requisition is interacted with, you attach that user_ID? Or when a response requisition is generated from a request requisition that was created at SAMES, it gets the request creator's user_ID?

**Comment by adrianwb** [comment]
Neither actually. I mean that it is possible for SAMES to enter response requisitions directly for any store without the store having had to generate an original request requisition (Customer -> Requisitions when logged into the SAMES store) - in that case, the user ID will be from the person who entered it.

**Comment by edmofro** [comment]
Ah, right! So what is the desktop site behaviour when a response
requisition syncs in as a result of a request requisition in another store
and site? We should replicate that in mobile. The first user to interact
with it gets attached in user_ID? Or does it always stay as the original
user attached to the initiating request requisition?
