### ISSUE TITLE
Sometimes Supplier Invoice are not being synced to other store correctly

### ISSUE THREAD

**Issue by nmadruga** [sussol/mobile#474]
Build Number: Build Number: current master (last commit 17/08/17 34a449a27baaab071b4817085c9bedb0282e3a1b)

Description: This one needs more investigation because it doesn't happen all the times. But sometimes, in that case. The Supplier Invoice should have been created on Store A when the Customer Invoice of Store B was finalised and synced. The Customer Invoice was made automatically in Store B after it received a requisition from Store A.

Reproducible: Sometimes

Reproduction Steps: With 2 mobiles running, make store A send request to store B. Then sync both. After that Store B will receive one Customer Invoice associated with that requisition (response requisition - Supply Stock ). Try to finalised it. Sync both, but the Supplier Invoice doesn't appear on Store A.

Comments:

**Comment by edmofro** [comment]
Need to mention @adrianwb here

**Comment by nmadruga** [comment]
Me and @DhanyaHerath have found something around that bug. The first time it works (doing the complete cycle of Supplier Requisition -> Customer Req. - finalise -> Supplier Invoice), and from the second time that's when the problem starts to happen and it doesn't get the Supplier Invoice anymore.
I'm going to check now if it is created in mSupply the second time.

**Comment by nmadruga** [comment]
Yes, I checked now and it's not creating the SI in that case in mSupply. If you can take a look on that, please @adrianwb

**Comment by edmofro** [comment]
@nmadruga I think it working the first time around is coincidental, because it didn't work even first time around for me.
