### ISSUE TITLE
Requisition lines disappear after Supplier Invoice is synced back to mobile store

### ISSUE THREAD

**Issue by DhanyaHerath** [sussol/mobile#477]
Build Number: current master (last commit 17/08/17 34a449a27baaab071b4817085c9bedb0282e3a1b) and mobile inter-store-requisition-cleanup branch.

Description: When a customer invoice is synced out from Store B and a Supplier Invoice is created in Store A following a request from Store A, the requisition lines on the original Supplier Requisition (in Store A) and the Customer Requisition (on Store B)  disappears on mobile. 

Reproducible: Always (as long as SI is being created on mobile) 

Reproduction Steps: With two mobiles running, create Supplier Requisition on Store A. Sync both stores to create Customer Requisition and Customer Invoice on Store B. Sync both stores again. If a supplier invoice is created in Store A, the requisition lines on the Supplier Requisition and Customer Requisition disappears, but the requisitions themselves remain (as in screenshots below.)

![screenshot_20170818-120904](https://user-images.githubusercontent.com/29744386/29438944-556ca59a-840e-11e7-894c-8fa4431d78f5.png)

<img width="937" alt="screen shot 2017-08-18 at 2 57 05 pm" src="https://user-images.githubusercontent.com/29744386/29442464-bf79b77c-8425-11e7-89de-73ab36c556f9.png">

Comments:
The Requisition and the Requisition lines are still there on the mSupply server, even after they have disappeared on mobile.

**Comment by Chris-Petty** [comment]
@edmofro off the hook, @andreievg takes full responsibility (and totally not me for letting it past review). Fixed in #481
