### ISSUE TITLE
Keyboard does not allow expiry date to be entered in SupplierInvoice item

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#482]
Build Number: v2.0.0 beta master https://github.com/sussol/mobile/commit/b7960b1f73cb49d13bc735f2a72802ed78a5ea5a

Description: On tab A, there is no '/' on the screen numpad so users can't enter dates for the expiry date field.

Reproducible: always

Reproduction Steps: 

Comments: Alex Bongers' suggestion is to have the field as 'mm/yyyy'. After the first 2 digits entered, the cursor should just move past the '/' so the user can start entering the year.

Alternative is just to add the slash to the keyboard provided to the user.

**Comment by andreievg** [comment]
https://github.com/sussol/mobile/pull/487

**Comment by edmofro** [comment]
Fixed by #487
