### ISSUE TITLE
RC9 - Pages UNRESPONSIVE

### ISSUE THREAD

**Issue by andreievg** [sussol/mobile#513]
I have only tested this in emulator, don't have access to tablet until tomorrow.

Every page is unresponsive, no verbose or error. (emulated with Genymotion, android 6 or 4)

Reproduction:
Go to SupplierInvoicePage, RequisitionPage, CustomerInvoicePage, etc.  Inputs seems to freeze, clicking on anything doesn't work,including hardware back button.

I really really hope it's my emulator playing up (or I've done something wrong). If it's not, then -> Team, no more merging or submiting PR's unless tested !!!

**Comment by DhanyaHerath** [comment]
Reproduced on tablet, app becomes unresponsive when on Create New Requisition/Invoice/Stocktake page.
