### ISSUE TITLE
Stocktake by batch

### ISSUE THREAD

**Issue by andreievg** [sussol/mobile#519]
Myanmar feature requirements, for version 2.1.0 -> Should be able do stock take by batch

Things to consider:

* Minimal or no changes to existing interface for current mobile users
  * Toggle for by [By Item][By Batch] -> this will work if batches are not deleted until finalisation (i.e. say there are two batches for the same item with quantity 50, when reducing quantity to 1 in [By Item], then switching to [By Batch], the batch that was emptied, remains with zero quantity
* Should be able to add new batch line
* On finalisation 0 stock batches to be removed

**Comment by Chris-Petty** [comment]
fixed in #542
