### ISSUE TITLE
App is crashing on back button of Supplier Invoice

### ISSUE THREAD

**Issue by nmadruga** [sussol/mobile#524]
Build Number: 2.0.0

Description: It happened 2 times today on my machine, should appear as developer mode then. It occurs when trying to go back on a supplier invoice (created before) without doing anything else.

Reproducible: Yes

Reproduction Steps: Go to Suplier Invoices > open one invoice > click to go back to Supplier invoices

Comments:

**Comment by Chris-Petty** [comment]
Maybe https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59b0f17398a452001a540a7c?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open

**Comment by nmadruga** [comment]
@Chris-Petty I think was only missing a "yarn install". Today I'm not getting the crash anymore

**Comment by Chris-Petty** [comment]
Cool. I've just tested now on tablet, seems to be working fine. Closing until new reports of it.
