### ISSUE TITLE
Finalising a customer invoice should delete 0 quantity items

### ISSUE THREAD

**Issue by edmofro** [sussol/mobile#532]
Just as it does for requisitions, stocktakes, etc., mSupply Mobile should be consistent by deleting any items left in a customer invoice with 0 quantity at the point it is finalised. This is helpful for when people add items from the master list but only actually issue a few of them.

**Comment by andreievg** [comment]
Funny timing, I also noticed this 10 mins ago.. and customer invoice can be finalised with one item, 0 quantity.

**Comment by edmofro** [comment]
Snap!

**Comment by andreievg** [comment]
you are too quick
