### ISSUE TITLE
undefined is not an object (evaluating 'this.props.currentTitle')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#538]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:338**
undefined is not an object (evaluating 'this.props.currentTitle')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/599e622e49b8e0001869e589?event_id=59dc2fd51b0eb0001c7fe47e&i=gh&m=ci)

## Stacktrace

    index.android.bundle:338 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/599e622e49b8e0001869e589?event_id=59dc2fd51b0eb0001c7fe47e&i=gh&m=ci)

*Created by Sustainable Solutions via Bugsnag*

**Comment by Chris-Petty** [comment]
@edmofro whoop whoop.

**Comment by edmofro** [comment]
Heyooooo @Chris-Petty

**Comment by Chris-Petty** [comment]
This error is being thrown very frequently post 2.0.0 (including sites running a rcX version).

**Comment by Chris-Petty** [comment]
Probably related is a similar [bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59b0a107c858c2001b369e6c?filters%5Berror.status%5D%5B%5D=open) for `this.props.runWithLoadingIndicator`

**Comment by edmofro** [comment]
I think you're right there. It'll be related to the change in the way page props are passed through, which used to be passed directly to each page from mSupplyMobileApp but now go through the react-navigation based Navigator.

**Comment by andreievg** [comment]
So I've managed to replicate this.props undefined error.  It's been the most frequent event in bugsnag, I think all of the following are related (undefined is not an object)
* this.props.runWithLoadingIndicator
* this.props.navigateTo
* this.props.currentTitle

And it's to do with a function loosing it's binding to `this` when bound with react-autobind.

Replication (Using branch in this pr, on tablet or emulator): 

https://github.com/sussol/mobile/pull/542
* make a stocktake with one item
* spam expansion on and off very quickly (app will crash within one minute)
* error message undefined is not an object, this.props.stocktakeItem 
* add a `console.log(!this.props)` in `renderAddBatchButton()` method
* you will see a `true` log just before the crash happens
* now add `this.renderAddBatchButton = this.renderAddBatchButton.bind(this);` after `autobind(this)`
* once again crash the app, there is not `true` logged now and crash jumps to `renderPageInfo`, which is the next component to be rendered after `renderAddBatchButton`. 
* can test further by manually binding `renderPageInfo`.

Will make an issue and a little test app for this in react-autobind repository.

Fixes.
* Back to manual binding for everything
* Using arrow function for all methods in our classes, i.e. `renderAddBatchButton = () => { ... }`, this feature is still experimental is ES, and may not be supported.. 
* Other options as per: https://daveceddia.com/avoid-bind-when-passing-props/
* Fixing `react-autobind`

`note:` no navigation in this test so it's no likely to be a problem with react-navigator`

**Comment by edmofro** [comment]
Good find drei! 

P.S. Tupaia MediTrak would love you if it was fixed in react-autobind ;-)
