### ISSUE TITLE
Bugsnag: Supplying Store Name ID missing from Settings

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#544]
## Error in mSupply Mobile

**Error** in **index.android.bundle:740**
Supplying Store Name ID missing from Settings

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e4098e5f8a0900187bf345?event_id=59e4098e5f8a0900187bf344&i=gh&m=ci)

## Stacktrace

    index.android.bundle:740 - migrate

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e4098e5f8a0900187bf345?event_id=59e4098e5f8a0900187bf344&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
@andreievg this occurred on 2.0.0-rc11. I'm pretty sure this has been resolved since right? If so please close.

**Comment by andreievg** [comment]
I am pretty sure it's been fixed when we stopped using autobind, closing.
