### ISSUE TITLE
Bugsnag: undefined is not an object (evaluating 'this.props.navigateTo')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#545]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:719**
undefined is not an object (evaluating 'this.props.navigateTo')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e5a29351c835001a3ec03e?event_id=59e5a29351c835001a3ec03d&i=gh&m=ci)

## Stacktrace

    index.android.bundle:719 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e5a29351c835001a3ec03e?event_id=59e5a29351c835001a3ec03d&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Fixed in #553
