### ISSUE TITLE
Bugsnag: undefined is not an object (evaluating 'this.props.runWithLoadingIndicator')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#546]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:660**
undefined is not an object (evaluating 'this.props.runWithLoadingIndicator')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e5e4965f2c16001a1c79c6?event_id=59e5e4965f2c16001a1c79c5&i=gh&m=ci)

## Stacktrace

    index.android.bundle:660 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e5e4965f2c16001a1c79c6?event_id=59e5e4965f2c16001a1c79c5&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Fixed in #553
