### ISSUE TITLE
Bugsnag: undefined is not a function (evaluating 'this.updateDataFilters(e,t,a)')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#547]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:718**
undefined is not a function (evaluating 'this.updateDataFilters(e,t,a)')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e6b321fa88c20019b3c1a8?event_id=59e6b321fa88c20019b3c1a7&i=gh&m=ci)

## Stacktrace

    index.android.bundle:718 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e6b321fa88c20019b3c1a8?event_id=59e6b321fa88c20019b3c1a7&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Maybe fixed in #553 ?

**Comment by andreievg** [comment]
Yeah, it should have been fixed in #553, if we see this after 2.1.0, will have to dig deep.
