### ISSUE TITLE
Bugsnag: undefined is not an object (evaluating 'this.props.stocktakeItem')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#548]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:734**
undefined is not an object (evaluating 'this.props.stocktakeItem')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e82ac962b767001941ce8b?event_id=59e82ac962b767001941ce8a&i=gh&m=ci)

## Stacktrace

    index.android.bundle:734 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59e82ac962b767001941ce8b?event_id=59e82ac962b767001941ce8a&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
fixed in #553
