### ISSUE TITLE
Bugsnag: undefined is not an object (evaluating 'i.batchesWithStock')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#558]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:717**
undefined is not an object (evaluating 'i.batchesWithStock')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59fa258ee1b29f001c1e05ac?event_id=59fa258ee1b29f001c1e05ab&i=gh&m=ci)

## Stacktrace

    index.android.bundle:717 - 

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59fa258ee1b29f001c1e05ac?event_id=59fa258ee1b29f001c1e05ab&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
I am pretty sure we fixed this.
