### ISSUE TITLE
Error in [native code]:0

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#561]
## Error in mSupply Mobile

**Error** in **[native code]:0**
Property 'otherPartyName' does not exist on object type 'Transaction'

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a0d02044145150019b02b0d?event_id=5a0d02044145150019b02b0c&i=gh&m=ci)

## Stacktrace

    [native code]:0 - sorted

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a0d02044145150019b02b0d?event_id=5a0d02044145150019b02b0c&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Closing as more recent duplicate
