### ISSUE TITLE
Bugsnag: undefined is not an object (evaluating 'this.props.navigateTo')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#566]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:719**
undefined is not an object (evaluating 'this.props.navigateTo')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a160658b97f6a001774ae5e?event_id=5a160658b97f6a001774ae5d&i=gh&m=ci)

## Stacktrace

    index.android.bundle:719 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a160658b97f6a001774ae5e?event_id=5a160658b97f6a001774ae5d&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Should be resolved in newer versions (where binding is fixed).

**Comment by sussol-invoices** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **index.android.bundle:719**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a160658b97f6a001774ae5e?event_id=5a160658b97f6a001774ae5d&i=gh&m=rm)

**Comment by sussol-invoices** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **index.android.bundle:719**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a160658b97f6a001774ae5e?event_id=5a160658b97f6a001774ae5d&i=gh&m=fx)
