### ISSUE TITLE
Bugsnag: java.lang.NullPointerException in DrawableContainer.java:823

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#567]
## Error in mSupply Mobile

**java.lang.NullPointerException** in **DrawableContainer.java:823**
Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.DrawableContainer$DrawableContainerState$ConstantStateFuture.get(android.graphics.drawable.DrawableContainer$DrawableContainerState)' on a null object reference

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59b67e5f3a2bff001b1997fe?event_id=5a16254923de450019283052&i=gh&m=ci)

## Stacktrace

    DrawableContainer.java:823 - android.graphics.drawable.DrawableContainer$DrawableContainerState.getChild

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/59b67e5f3a2bff001b1997fe?event_id=5a16254923de450019283052&i=gh&m=ci)

*Created by Sustainable Solutions via Bugsnag*

**Comment by Chris-Petty** [comment]
Closed similar for 2.0.0. Might occur on a newer version, or hopefully not!
