### ISSUE TITLE
Error in [native code]:0

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#568]
## Error in mSupply Mobile

**Error** in **[native code]:0**
Property 'otherPartyName' does not exist on object type 'Transaction'

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a178980a3d4d80018482b33?event_id=5a178980a3d4d80018482b32&i=gh&m=ci)

## Stacktrace

    [native code]:0 - sorted

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a178980a3d4d80018482b33?event_id=5a178980a3d4d80018482b32&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Duplicate of #561

**Comment by Chris-Petty** [comment]
Bugsnag is a bit dumb, there is another bug that is throwing "Error in [native code]:0"

> Property 'countedTotalQuantity' does not exist on object type 'StocktakeItem'

This is the error causing crashing on sorting `Actual Quantity` on stocktakes #617 
May also be causing weird issue of entered values being clear if you edit and existing one for `Actual Quantity`.

**Comment by Chris-Petty** [comment]
fixed #627

**Comment by sussol-invoices** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **[native code]:0**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a178980a3d4d80018482b33?event_id=5ae15be1a9227d00182c7a17&i=gh&m=ra)

**Comment by sussol-invoices** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **[native code]:0**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a178980a3d4d80018482b33?event_id=5ae15be2720893001af0349e&i=gh&m=fx)

**Comment by sussol-invoices** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **&#91;native code&#93;:0**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a178980a3d4d80018482b33?event_id=5b3d6d9a6f2da40019d0affd&i=gh&m=ra)

**Comment by sussol-invoices** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **&#91;native code&#93;:0**](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a178980a3d4d80018482b33?event_id=5b3d7e288c10740018c707ce&i=gh&m=fx)

**Comment by Chris-Petty** [comment]
Resolved, was bug with me developing an export in #692

![image](https://user-images.githubusercontent.com/7684221/42360796-1c27337a-813f-11e8-98e4-0bacfb9d3ad0.png)
