### ISSUE TITLE
Bugsnag: undefined is not a function (evaluating 'this.openModal(b.ITEM_SELECT)')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#569]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:733**
undefined is not a function (evaluating 'this.openModal(b.ITEM_SELECT)')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a1b641ec1dcbc001a6acf02?event_id=5a1b641ec1dcbc001a6acf01&i=gh&m=ci)

## Stacktrace

    index.android.bundle:733 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a1b641ec1dcbc001a6acf02?event_id=5a1b641ec1dcbc001a6acf01&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
@andreievg Active in your dev/RC branch?

**Comment by Chris-Petty** [comment]
Probably autobind issue
