### ISSUE TITLE
Bugsnag: null is not an object (evaluating 'this.itemBatch.item')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#570]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:707**
null is not an object (evaluating 'this.itemBatch.item')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a20ced3e66c9a0019dce1c9?event_id=5a20ced3e66c9a0019dce1c8&i=gh&m=ci)

## Stacktrace

    index.android.bundle:707 - get

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a20ced3e66c9a0019dce1c9?event_id=5a20ced3e66c9a0019dce1c8&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Stale. Data issue. Caused by mobile...? Not enough to know. Closed for now.
