### ISSUE TITLE
Current stock shows no number for 0 stock

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#573]
Build Number: 2.1.0

Description: 
Current stock shows no number for 0 stock

Reproducible: Yes

Reproduction Steps: Look at current stock
![image](https://user-images.githubusercontent.com/7684221/33578251-d30f22ba-d9aa-11e7-93e5-c6cf84a738fd.png)

Comments: Something passive aggressive about testing

**Comment by andreievg** [comment]
Fixed in https://github.com/sussol/mobile/pull/580
