### ISSUE TITLE
Can double finalise stocktake - stocktake makes double quantity changes

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#574]
Build Number: 2.0.0 and RC11, perhaps all earlier

Description:
When entering a finalising a stocktake, it is possible to click the confirm button in the finalise modal twice with a double tap. This will create any transactions with 2 trans lines for every adjustment in the stocktake, effectively doubling the change.

Reproducible: Yes

Reproduction Steps:
1. Create a stock take with a couple dozen lines with quantity changes (preferably from 0, to say 100)
2. Press finalise
3. Double tap confirm
4. Check in stock and see that quantities have had twice the difference applied. Say it should have gone from 0 to 100, it will have gone from 0 to 200.

Comments:
When synced to mSupply Desktop, you can login to the mobile store and check inventory adjustments. Here you can see the transaction corresponding to the stocktake. It will have 2 lines for every item adjusted, with the same adjustment value.

**Comment by andreievg** [comment]
This has caused a ledger problem in MAM, looks like multiple TransactionBatches are created on mobile for the same item adjustment. Because `Spinner` modal/overlay is 'see-through' in term of onPress events
@edmofro just a heads up if you are using `Spinner` in other projects.
