### ISSUE TITLE
Cannot enter value equal to snapshot in stocktake

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#575]
Build Number: 2.1.0

Description:
When editing a stocktake, you cannot enter a value equal to the snapshot value. It will revert to "Not counted".

Reproducible: Yes

Reproduction Steps: Get version. Do it.

Comments:

**Comment by andreievg** [comment]
https://github.com/sussol/mobile/releases/tag/v2.1.0-rc4
