### ISSUE TITLE
Bugsnag: null is not an object (evaluating 'this.itemBatch.item')

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#586]
## Error in mSupply Mobile

**TypeError** in **index.android.bundle:694**
null is not an object (evaluating 'this.itemBatch.item')

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a3b347eada2b400189095dc?event_id=5a3b347eada2b400189095db&i=gh&m=ci)

## Stacktrace

    index.android.bundle:694 - get

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a3b347eada2b400189095dc?event_id=5a3b347eada2b400189095db&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
I believe this is fixed in more recent versions.
