### ISSUE TITLE
Bugsnag: Supplying Store Name ID missing from Settings

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#587]
## Error in mSupply Mobile

**Error** in **index.android.bundle:740**
Supplying Store Name ID missing from Settings

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a3ec9a78917cf00191a00ae?event_id=5a3ec9a78917cf00191a00ad&i=gh&m=ci)

## Stacktrace

    index.android.bundle:740 - migrate

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5a3ec9a78917cf00191a00ae?event_id=5a3ec9a78917cf00191a00ad&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Closed as no longer on bugsnag. Should come up as new issue if it occurs again.
