### ISSUE TITLE
Bugsnag: Cannot finalise as transaction is already finalised

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#633]
## Error in mSupply Mobile

**Error** in **index.android.bundle:707**
Cannot finalise as transaction is already finalised

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5aa9d01e46a8a6001873f36e?event_id=5aa9d01e46a8a6001873f36d&i=gh&m=ci)

## Stacktrace

    index.android.bundle:707 - value

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5aa9d01e46a8a6001873f36e?event_id=5aa9d01e46a8a6001873f36d&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
This must be happening in Solomons as I believe they are the only ones with the SM-P555 tablets. 

Need to either figure out how this happening or wait for a user to report reproduction steps.

bugsnag reference:
![image](https://user-images.githubusercontent.com/7684221/37443809-4b0d7336-2873-11e8-81e6-3459470b0f75.png)

**Comment by Chris-Petty** [comment]
probably able to to just double tap finalise through the spinner modal. Second tap doesn't work because of this error. Bugsnag 404...
