### ISSUE TITLE
java.lang.IllegalArgumentException in Request.java:142

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#641]
## Error in mSupply Mobile

**java.lang.IllegalArgumentException** in **Request.java:142**
unexpected url: http://:8089/sync/v3/site

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5aba135fd7f48e0018f10f6a?event_id=5aba135fd7f48e0018f10f69&i=gh&m=ci)

## Stacktrace

    Request.java:142 - okhttp3.Request$Builder.url

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5aba135fd7f48e0018f10f6a?event_id=5aba135fd7f48e0018f10f69&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Just user input fail.
