### ISSUE TITLE
java.lang.RuntimeException in JavaMethodWrapper.java:374

### ISSUE THREAD

**Issue by sussol-invoices** [sussol/mobile#723]
## Error in mSupply Mobile

**java.lang.RuntimeException** in **JavaMethodWrapper.java:374**
Could not invoke NativeAnimatedModule.dropAnimatedNode

[View on Bugsnag](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5b89d42fb657f0001dcf1e38?event_id=5b89d42f002dd118dbae0000&i=gh&m=ci)

## Stacktrace

    JavaMethodWrapper.java:374 - com.facebook.react.bridge.JavaMethodWrapper.invoke

[View full stacktrace](https://app.bugsnag.com/sustainable-solutions-nz-ltd/msupply-mobile/errors/5b89d42fb657f0001dcf1e38?event_id=5b89d42f002dd118dbae0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by Chris-Petty** [comment]
Old RC version and bugsnag 404s.
