### ISSUE TITLE
Update dependancies

### ISSUE THREAD

**Issue by Chris-Petty** [sussol/mobile#740]
Build Number: 2.1.1

Description: 
As you can read [here](http://facebook.github.io/react-native/blog/2018/07/04/releasing-react-native-056#modernizing-android-support) in an official RN blog from July, to publish on the android store we'll need to upgrade mSupply Mobile to run on at least RN 0.56 if we are to update the app published on the app store next month, or possibly already need to because it's currently unpublished (I think that's their terminology).

So:
- [x] Update react-native to at least 0.56 (0.57 is the latest). You'll need to follow the release notes of each release of RN to make sure any require changes (if any) are met!
- [x] Update the rest of dependancies where necessary or convenient. Some will likely have peer dependancies tied to react/RN versions. Yarn has a bunch of useful cli commands such as `yarn outdated` and `yarn upgradeInteractive`.

Comments:
- Probably be incremental with your commits, so you can peel back if certain sets of modules are incompatible.
- ListView is deprecated, but probably still available in RN 0.56. If it's fully cut from RN API we'll need to commit to rewriting react-native-data-table with FlatList, too.

**Comment by sworupSussol** [comment]
https://github.com/sussol/mobile/pull/741

**Comment by sworup** [comment]
I think we can close this.
